# Generated by Django 4.2.5 on 2024-02-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_single'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='HomeCategory',
        ),
        migrations.AddField(
            model_name='single',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.author'),
            preserve_default=False,
        ),
    ]
