# Generated by Django 4.2.5 on 2024-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_posts_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Single',
        ),
    ]
