# Generated by Django 4.2.5 on 2024-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contactus_newsteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='addfile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
