# Generated by Django 4.2.5 on 2024-02-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactus_addfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='NewsTeam',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
