# Generated by Django 4.2.5 on 2024-02-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_author_contactus_newsteam_sendpost_video_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='NewsTeam',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.DeleteModel(
            name='SendPost',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
