# Generated by Django 4.2.5 on 2024-02-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Edit',
        ),
        migrations.DeleteModel(
            name='NewsTeam',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.DeleteModel(
            name='SendPost',
        ),
        migrations.DeleteModel(
            name='SendVideo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
