# Generated by Django 4.2.5 on 2024-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_aboutus_author_contactus_edit_newsteam_sendpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='addbanner',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='addimage',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='explanation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='oldpassword',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='password',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edit',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
